###############################################################
#  Generated by:      Cadence Encounter 09.10-p004_1
#  OS:                Linux i686(Host ID esl2-5)
#  Generated on:      Thu Nov 21 10:49:03 2013
#  Command:           floorPlan -su 1 0.9 4 4 4 4
###############################################################

Version: 8

Head Box: 0.0000 0.0000 89.7700 89.2600
IO Box: 0.0000 0.0000 89.7700 89.2600
Core Box: 4.1800 4.0600 85.7700 85.2600
UseStdUtil: true

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: FreePDK45_38x28_10R_NP_162NW_34O 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 4.0600 FS 429 1 0.1900 0.0000
DefRow: ROW_1 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 5.4600 N 429 1 0.1900 0.0000
DefRow: ROW_2 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 6.8600 FS 429 1 0.1900 0.0000
DefRow: ROW_3 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 8.2600 N 429 1 0.1900 0.0000
DefRow: ROW_4 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 9.6600 FS 429 1 0.1900 0.0000
DefRow: ROW_5 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 11.0600 N 429 1 0.1900 0.0000
DefRow: ROW_6 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 12.4600 FS 429 1 0.1900 0.0000
DefRow: ROW_7 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 13.8600 N 429 1 0.1900 0.0000
DefRow: ROW_8 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 15.2600 FS 429 1 0.1900 0.0000
DefRow: ROW_9 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 16.6600 N 429 1 0.1900 0.0000
DefRow: ROW_10 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 18.0600 FS 429 1 0.1900 0.0000
DefRow: ROW_11 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 19.4600 N 429 1 0.1900 0.0000
DefRow: ROW_12 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 20.8600 FS 429 1 0.1900 0.0000
DefRow: ROW_13 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 22.2600 N 429 1 0.1900 0.0000
DefRow: ROW_14 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 23.6600 FS 429 1 0.1900 0.0000
DefRow: ROW_15 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 25.0600 N 429 1 0.1900 0.0000
DefRow: ROW_16 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 26.4600 FS 429 1 0.1900 0.0000
DefRow: ROW_17 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 27.8600 N 429 1 0.1900 0.0000
DefRow: ROW_18 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 29.2600 FS 429 1 0.1900 0.0000
DefRow: ROW_19 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 30.6600 N 429 1 0.1900 0.0000
DefRow: ROW_20 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 32.0600 FS 429 1 0.1900 0.0000
DefRow: ROW_21 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 33.4600 N 429 1 0.1900 0.0000
DefRow: ROW_22 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 34.8600 FS 429 1 0.1900 0.0000
DefRow: ROW_23 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 36.2600 N 429 1 0.1900 0.0000
DefRow: ROW_24 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 37.6600 FS 429 1 0.1900 0.0000
DefRow: ROW_25 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 39.0600 N 429 1 0.1900 0.0000
DefRow: ROW_26 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 40.4600 FS 429 1 0.1900 0.0000
DefRow: ROW_27 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 41.8600 N 429 1 0.1900 0.0000
DefRow: ROW_28 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 43.2600 FS 429 1 0.1900 0.0000
DefRow: ROW_29 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 44.6600 N 429 1 0.1900 0.0000
DefRow: ROW_30 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 46.0600 FS 429 1 0.1900 0.0000
DefRow: ROW_31 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 47.4600 N 429 1 0.1900 0.0000
DefRow: ROW_32 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 48.8600 FS 429 1 0.1900 0.0000
DefRow: ROW_33 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 50.2600 N 429 1 0.1900 0.0000
DefRow: ROW_34 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 51.6600 FS 429 1 0.1900 0.0000
DefRow: ROW_35 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 53.0600 N 429 1 0.1900 0.0000
DefRow: ROW_36 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 54.4600 FS 429 1 0.1900 0.0000
DefRow: ROW_37 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 55.8600 N 429 1 0.1900 0.0000
DefRow: ROW_38 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 57.2600 FS 429 1 0.1900 0.0000
DefRow: ROW_39 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 58.6600 N 429 1 0.1900 0.0000
DefRow: ROW_40 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 60.0600 FS 429 1 0.1900 0.0000
DefRow: ROW_41 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 61.4600 N 429 1 0.1900 0.0000
DefRow: ROW_42 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 62.8600 FS 429 1 0.1900 0.0000
DefRow: ROW_43 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 64.2600 N 429 1 0.1900 0.0000
DefRow: ROW_44 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 65.6600 FS 429 1 0.1900 0.0000
DefRow: ROW_45 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 67.0600 N 429 1 0.1900 0.0000
DefRow: ROW_46 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 68.4600 FS 429 1 0.1900 0.0000
DefRow: ROW_47 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 69.8600 N 429 1 0.1900 0.0000
DefRow: ROW_48 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 71.2600 FS 429 1 0.1900 0.0000
DefRow: ROW_49 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 72.6600 N 429 1 0.1900 0.0000
DefRow: ROW_50 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 74.0600 FS 429 1 0.1900 0.0000
DefRow: ROW_51 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 75.4600 N 429 1 0.1900 0.0000
DefRow: ROW_52 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 76.8600 FS 429 1 0.1900 0.0000
DefRow: ROW_53 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 78.2600 N 429 1 0.1900 0.0000
DefRow: ROW_54 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 79.6600 FS 429 1 0.1900 0.0000
DefRow: ROW_55 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 81.0600 N 429 1 0.1900 0.0000
DefRow: ROW_56 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 82.4600 FS 429 1 0.1900 0.0000
DefRow: ROW_57 FreePDK45_38x28_10R_NP_162NW_34O 4.1800 83.8600 N 429 1 0.1900 0.0000

######################################################
#  Track: dir start number space layer_num layer1 ...#
######################################################
Track: Y 0.9300 56 1.6000 1 10
Track: X 0.9150 53 1.6800 1 10
Track: X 0.9150 106 0.8400 1 9
Track: Y 0.9300 56 1.6000 1 9
Track: Y 0.7700 106 0.8400 1 8
Track: X 0.9150 106 0.8400 1 8
Track: X 0.3550 320 0.2800 1 7
Track: Y 0.7700 106 0.8400 1 7
Track: Y 0.2100 319 0.2800 1 6
Track: X 0.3550 320 0.2800 1 6
Track: X 0.3550 320 0.2800 1 5
Track: Y 0.2100 319 0.2800 1 5
Track: Y 0.0700 638 0.1400 1 4
Track: X 0.3550 320 0.2800 1 4
Track: X 0.0950 472 0.1900 1 3
Track: Y 0.0700 638 0.1400 1 3
Track: Y 0.0700 638 0.1400 1 2
Track: X 0.0950 472 0.1900 1 2
Track: X 0.0950 472 0.1900 1 1
Track: Y 0.0700 638 0.1400 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 89.3950 2 0.3750
GCellGrid: X 0.0950 48 1.9000
GCellGrid: X 0.0000 2 0.0950
GCellGrid: Y 88.2700 2 0.9900
GCellGrid: Y 0.0700 64 1.4000
GCellGrid: Y 0.0000 2 0.0700

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val isAltLayer=val isPffGroup=val > #
#         <Net name="net_name" /> ...                                     #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval coreToBottom=fval   #
#         pinSpacingNorth=val pinSpacingWest=val pinSpacingSouth=val      #
#         pinSpacingEast=val  blockedLayers=xval >       #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name"                    #
#                       pins=nr spacing=val isOptOrder=1 isAltLayer=1 >   #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num cell="name" >                       #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <Partition name="RegFile" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=2 pinSpacingWest=2 pinSpacingSouth=2 pinSpacingEast=2 blockedLayers=0x3ff >
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
    </Partition>
</HierarchicalPartitions>

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

#################################################################
#  <PlacementBlockages>                                         #
#     <Blockage name="blk_name" type="hard|soft|partial">       #
#       <Attr density=1.2 inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </PlacementBlockages>                                        #
#################################################################

###########################################################################
#  <RouteBlockages>                                                       #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">   #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes />   #
#       <Layer type="route|cut|masterslice" id=layerNo />                 #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                       #
#     </Blockage>                                                         #
#  </RouteBlockages>                                                      #
###########################################################################

######################################################
#  PrerouteAsObstruct: <layer_treated_as_obstruct>   #
######################################################
PrerouteAsObstruct: 0x3

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .RegFile32182.rs.fp.spr

##########################################################################
#  <IOPins>                                                              #
#    <Pin name="pin_name" type="clock|power|ground|analog"               #
#         status="covered|fixed|placed" is_special=1 >                   #
#      <Port>                                                            #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d />             #
#        <Via name="via_name" x=1 y=2 /> ...                             #
#        <Layer id=id spacing=1.2 drw=1.2>                               #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                           #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />          #
#        </Layer> ...                                                    #
#      </Port>  ...                                                      #
#      <Antenna model=num type="name" value=float_num layer=num /> ...   #
#    </Pin> ...                                                          #
#  </IOPins>                                                             #
##########################################################################

<IOPins>
  <Pin name="addressA[4]" status="fixed" >
    <Port>
      <Pref x=32.7750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=32.7400 lly=89.1900 urx=32.8100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressA[3]" status="fixed" >
    <Port>
      <Pref x=31.8250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=31.7900 lly=89.1900 urx=31.8600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressA[2]" status="fixed" >
    <Port>
      <Pref x=30.8750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=30.8400 lly=89.1900 urx=30.9100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressA[1]" status="fixed" >
    <Port>
      <Pref x=29.9250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=29.8900 lly=89.1900 urx=29.9600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressA[0]" status="fixed" >
    <Port>
      <Pref x=28.9750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=28.9400 lly=89.1900 urx=29.0100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressB[4]" status="fixed" >
    <Port>
      <Pref x=37.5250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=37.4900 lly=89.1900 urx=37.5600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressB[3]" status="fixed" >
    <Port>
      <Pref x=36.5750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=36.5400 lly=89.1900 urx=36.6100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressB[2]" status="fixed" >
    <Port>
      <Pref x=35.6250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=35.5900 lly=89.1900 urx=35.6600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressB[1]" status="fixed" >
    <Port>
      <Pref x=34.6750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=34.6400 lly=89.1900 urx=34.7100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressB[0]" status="fixed" >
    <Port>
      <Pref x=33.7250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=33.6900 lly=89.1900 urx=33.7600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[15]" status="fixed" >
    <Port>
      <Pref x=52.7250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=52.6900 lly=89.1900 urx=52.7600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[14]" status="fixed" >
    <Port>
      <Pref x=51.7750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=51.7400 lly=89.1900 urx=51.8100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[13]" status="fixed" >
    <Port>
      <Pref x=50.8250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=50.7900 lly=89.1900 urx=50.8600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[12]" status="fixed" >
    <Port>
      <Pref x=49.8750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=49.8400 lly=89.1900 urx=49.9100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[11]" status="fixed" >
    <Port>
      <Pref x=48.9250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=48.8900 lly=89.1900 urx=48.9600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[10]" status="fixed" >
    <Port>
      <Pref x=47.9750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=47.9400 lly=89.1900 urx=48.0100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[9]" status="fixed" >
    <Port>
      <Pref x=62.7950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=62.7600 lly=0.0000 urx=62.8300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[8]" status="fixed" >
    <Port>
      <Pref x=46.0750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=46.0400 lly=89.1900 urx=46.1100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[7]" status="fixed" >
    <Port>
      <Pref x=45.1250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=45.0900 lly=89.1900 urx=45.1600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[6]" status="fixed" >
    <Port>
      <Pref x=44.1750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=44.1400 lly=89.1900 urx=44.2100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[5]" status="fixed" >
    <Port>
      <Pref x=43.2250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=43.1900 lly=89.1900 urx=43.2600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[4]" status="fixed" >
    <Port>
      <Pref x=42.2750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=42.2400 lly=89.1900 urx=42.3100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[3]" status="fixed" >
    <Port>
      <Pref x=41.3250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=41.2900 lly=89.1900 urx=41.3600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[2]" status="fixed" >
    <Port>
      <Pref x=40.3750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=40.3400 lly=89.1900 urx=40.4100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[1]" status="fixed" >
    <Port>
      <Pref x=39.4250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=39.3900 lly=89.1900 urx=39.4600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="dataIn[0]" status="fixed" >
    <Port>
      <Pref x=38.4750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=38.4400 lly=89.1900 urx=38.5100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressIn[4]" status="fixed" >
    <Port>
      <Pref x=57.4750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=57.4400 lly=89.1900 urx=57.5100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressIn[3]" status="fixed" >
    <Port>
      <Pref x=56.5250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=56.4900 lly=89.1900 urx=56.5600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressIn[2]" status="fixed" >
    <Port>
      <Pref x=55.5750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=55.5400 lly=89.1900 urx=55.6100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressIn[1]" status="fixed" >
    <Port>
      <Pref x=54.6250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=54.5900 lly=89.1900 urx=54.6600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="addressIn[0]" status="fixed" >
    <Port>
      <Pref x=53.6750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=53.6400 lly=89.1900 urx=53.7100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="clk" status="fixed" >
    <Port>
      <Pref x=58.4250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=58.3900 lly=89.1900 urx=58.4600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="reset" status="fixed" >
    <Port>
      <Pref x=59.3750 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=59.3400 lly=89.1900 urx=59.4100 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="write" status="fixed" >
    <Port>
      <Pref x=60.3250 y=89.2600 side=N width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=60.2900 lly=89.1900 urx=60.3600 ury=89.2600 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[15]" status="fixed" >
    <Port>
      <Pref x=43.7950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=43.7600 lly=0.0000 urx=43.8300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[14]" status="fixed" >
    <Port>
      <Pref x=41.8950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=41.8600 lly=0.0000 urx=41.9300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[13]" status="fixed" >
    <Port>
      <Pref x=39.9950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=39.9600 lly=0.0000 urx=40.0300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[12]" status="fixed" >
    <Port>
      <Pref x=38.0950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=38.0600 lly=0.0000 urx=38.1300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[11]" status="fixed" >
    <Port>
      <Pref x=36.1950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=36.1600 lly=0.0000 urx=36.2300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[10]" status="fixed" >
    <Port>
      <Pref x=34.2950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=34.2600 lly=0.0000 urx=34.3300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[9]" status="fixed" >
    <Port>
      <Pref x=32.3950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=32.3600 lly=0.0000 urx=32.4300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[8]" status="fixed" >
    <Port>
      <Pref x=30.4950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=30.4600 lly=0.0000 urx=30.5300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[7]" status="fixed" >
    <Port>
      <Pref x=28.5950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=28.5600 lly=0.0000 urx=28.6300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[6]" status="fixed" >
    <Port>
      <Pref x=26.6950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=26.6600 lly=0.0000 urx=26.7300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[5]" status="fixed" >
    <Port>
      <Pref x=24.7950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=24.7600 lly=0.0000 urx=24.8300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[4]" status="fixed" >
    <Port>
      <Pref x=22.8950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=22.8600 lly=0.0000 urx=22.9300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[3]" status="fixed" >
    <Port>
      <Pref x=20.9950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=20.9600 lly=0.0000 urx=21.0300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[2]" status="fixed" >
    <Port>
      <Pref x=19.0950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=19.0600 lly=0.0000 urx=19.1300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[1]" status="fixed" >
    <Port>
      <Pref x=17.1950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=17.1600 lly=0.0000 urx=17.2300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outA[0]" status="fixed" >
    <Port>
      <Pref x=15.2950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=15.2600 lly=0.0000 urx=15.3300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[15]" status="fixed" >
    <Port>
      <Pref x=74.1950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=74.1600 lly=0.0000 urx=74.2300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[14]" status="fixed" >
    <Port>
      <Pref x=72.2950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=72.2600 lly=0.0000 urx=72.3300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[13]" status="fixed" >
    <Port>
      <Pref x=70.3950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=70.3600 lly=0.0000 urx=70.4300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[12]" status="fixed" >
    <Port>
      <Pref x=68.4950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=68.4600 lly=0.0000 urx=68.5300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[11]" status="fixed" >
    <Port>
      <Pref x=66.5950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=66.5600 lly=0.0000 urx=66.6300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[10]" status="fixed" >
    <Port>
      <Pref x=64.6950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=64.6600 lly=0.0000 urx=64.7300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[8]" status="fixed" >
    <Port>
      <Pref x=60.8950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=60.8600 lly=0.0000 urx=60.9300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[7]" status="fixed" >
    <Port>
      <Pref x=58.9950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=58.9600 lly=0.0000 urx=59.0300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[6]" status="fixed" >
    <Port>
      <Pref x=57.0950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=57.0600 lly=0.0000 urx=57.1300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[5]" status="fixed" >
    <Port>
      <Pref x=55.1950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=55.1600 lly=0.0000 urx=55.2300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[4]" status="fixed" >
    <Port>
      <Pref x=53.2950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=53.2600 lly=0.0000 urx=53.3300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[3]" status="fixed" >
    <Port>
      <Pref x=51.3950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=51.3600 lly=0.0000 urx=51.4300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[2]" status="fixed" >
    <Port>
      <Pref x=49.4950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=49.4600 lly=0.0000 urx=49.5300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[1]" status="fixed" >
    <Port>
      <Pref x=47.5950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=47.5600 lly=0.0000 urx=47.6300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
  <Pin name="outB[0]" status="fixed" >
    <Port>
      <Pref x=45.6950 y=0.0000 side=S width=0.0700 depth=0.0700 />
      <Layer id=2 >
        <Box llx=45.6600 lly=0.0000 urx=45.7300 ury=0.0700 />
      </Layer>
    </Port>
  </Pin>
</IOPins>

####################################################################################################
#  PGPin: <pin> <net> {in|out|inout} {pwr|gnd|-} {placed|fixed|-} <x> <y> <side> <layerId> <nrBox> #
#    PinBox: <llx> <lly> <urx> <ury>                                                               #
#    PinPoly: <nrPts> <x1> <y1> <x2> <y2>...<xn> <yn>                                              #
####################################################################################################
PGPin: VDD VDD inout pwr fixed 2.7800 0.0000 S 10 1
  PinBox: 2.3800 0.0000 3.1800 0.8000 -lyr 10
PGPin: VDD VDD inout pwr fixed 2.7800 89.2600 N 10 1
  PinBox: 2.3800 88.4600 3.1800 89.2600 -lyr 10
PGPin: VDD VDD inout pwr fixed 87.0900 0.0000 S 10 1
  PinBox: 86.6900 0.0000 87.4900 0.8000 -lyr 10
PGPin: VDD VDD inout pwr fixed 87.0900 89.2600 N 10 1
  PinBox: 86.6900 88.4600 87.4900 89.2600 -lyr 10
PGPin: VSS VSS inout gnd fixed 1.1800 0.0000 S 10 1
  PinBox: 0.7800 0.0000 1.5800 0.8000 -lyr 10
PGPin: VSS VSS inout gnd fixed 1.1800 89.2600 N 10 1
  PinBox: 0.7800 88.4600 1.5800 89.2600 -lyr 10
PGPin: VSS VSS inout gnd fixed 88.6900 0.0000 S 10 1
  PinBox: 88.2900 0.0000 89.0900 0.8000 -lyr 10
PGPin: VSS VSS inout gnd fixed 88.6900 89.2600 N 10 1
  PinBox: 88.2900 88.4600 89.0900 89.2600 -lyr 10

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="RegFile">
	<prop name="CUT_ROWS" type=Int value=0 />
  </Design>
</Properties>

###########################################################$############################################################################################
#  GlobalNetConnection: <net_name> {-pin|-inst|-net} <base_name_pattern> -type {pgpin|net|tiehi|tielo} {-all|-module <name>|-region <box>} [-override] #
########################################################################################################################################################
GlobalNetConnection: VDD -pin VDD -type pgpin -all
GlobalNetConnection: VSS -pin VSS -type pgpin -all

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################
